server:
  port: 4000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

